---
title: "eerste analyse"
author: "Steven Wallaert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, tidy=TRUE)
```




```{r}
library(tidyverse)

files <- dir("output/")
files_detect <- files[str_detect(files, "detect.csv$")]

df_detect <- map_df(files_detect, function(x){
  read_csv(paste0("output/", x))
})

files_perf <- files[str_detect(files, "perf.csv$")]
df_perf <- map_df(files_perf, function(x){
  read_csv(paste0("output/", x))
})

files_null <- files[str_detect(files, "null.csv$")]
df_null <- map_df(files_null, function(x){
  read_csv(paste0("output/", x))
})

files_time <- files[str_detect(files, "time.csv$")]
df_time <- map_df(files_time, function(x){
  read_csv(paste0("output/", x))
})
```

## Mean number of discoveries: per type (True/False) and method

```{r, fig.width=10}

df_detect %>%
filter(d == 0.95, nsims == 100, sig_p == 3, n == 30, correlated == "block") %>%
#filter(! method %in% c("svm", "tweedie")) %>%
ggplot(aes(x=p, y=mean_nr, fill=detection)) +
geom_col(position = "dodge", show.legend = F) +
geom_errorbar(aes(ymin=mean_nr-1.96*mean_se, ymax=mean_nr+1.96*mean_se), width = 0.3) +
scale_x_log10(breaks=c(100,300,1000,3000,1e4) )  +
facet_grid(detection~method, scales="free", labeller = labeller(method = c("boruta" = "Boruta",
                                                                           "fdr" = "t-test + FDR",
                                                                           "lasso" = "Logistic Lasso",
                                                                           "svm" = "SVMRFE top 1%",
                                                                           "tweedie" = "t-test + Tweedie"))) +
  labs(x = "Number of features",
       y = "Mean number of discoveries") +
  theme_bw()


```

```{r}
d_ <- 1.1
nsims_ <- 100
sig_p_ <- 10
n_ <- 50
correlated_ <- "no"


df_detect %>%
filter(d == d_, nsims == nsims_, sig_p == sig_p_, n == n_, correlated == correlated_) %>%
ggplot(aes(x=p, y=mean_nr)) +
geom_point(aes(color = method)) +
geom_line(aes(group = method, color = method)) +
geom_errorbar(aes(ymin=mean_nr-1.96*mean_se, ymax=mean_nr+1.96*mean_se, color = method), width = 0.1, alpha = 0.7) +
scale_x_log10(breaks=c(100,300,1000,3000,1e4), labels = scales::comma_format() )  +
facet_grid(detection~., scales="free", labeller = labeller(method = c("boruta" = "Boruta",
                                                                           "fdr" = "t-test + FDR",
                                                                           "lasso" = "Logistic Lasso",
                                                                           "svm" = "SVMRFE top 1%",
                                                                           "tweedie" = "t-test + Tweedie"))) +
  labs(x = "Number of features",
       y = "Mean number of discoveries",
       title = paste0("n = ", n_, ", sig_p = ", sig_p_, ", d = ", d_, ", ", correlated_, " correlation")) +
  theme_bw() +
  scale_y_log10() +
  scale_color_brewer(palette = "Set1") +
  geom_hline(yintercept = 10, color = "grey", lty = "dashed") +
  geom_label_repel(data = df_detect %>%
  filter(d == d_, nsims == nsims_, n == n_, sig_p == sig_p_, correlated == correlated_, p == 10000), aes(label = method, color = method)) +
  theme(legend.position = "none")

```


```{r, fig.width=8}
df_detect %>%
  filter(d == 1.81) %>%
  filter(! method %in% c("svm", "tweedie")) %>%
  ggplot(aes(x=p, y=mean_nr, fill=detection)) +
  geom_col(position = "dodge", show.legend = F) +
  geom_errorbar(aes(ymin=mean_nr-1.96*mean_se, ymax=mean_nr+1.96*mean_se), width = 0.3) +
  scale_x_log10(breaks=c(100,300,1000,3000,1e4))  +
  facet_grid(detection~method, scales="free")
```



```{r, fig.width=8}
df_detect %>%
  filter(d == 1.81) %>%
  filter(method %in% c("svm", "tweedie")) %>%
  ggplot(aes(x=p, y=mean_nr, fill=detection)) +
  geom_col(position = "dodge", show.legend = F) +
  geom_errorbar(aes(ymin=mean_nr-1.96*mean_se, ymax=mean_nr+1.96*mean_se), width = 0.3) +
  scale_x_log10(breaks=c(100,300,1000,3000,1e4))  +
  facet_grid(detection~method, scales="free")
```

## Chance of a detection

```{r, fig.width=10}
df_detect %>%
  filter(d == 0.1, nsims == 10) %>%
  ggplot(aes(x = p, y=a_detection, fill=detection)) +
  geom_col(show.legend = F) +
  geom_errorbar(aes(ymin =a_detection - 1.96*a_det_se, ymax= a_detection + 1.96*a_det_se), width = 0.3) +
  scale_x_log10(breaks=c(10,30,100,300,1000,3000,1e4,3e4)) +
  facet_grid(detection~method) +
  lims(y = c(-0.1,1.1))
```

```{r}
library(ggrepel)
df_detect %>%
  filter(d == 0.5, nsims == 10, n == 76, is.na(correlated)) %>%
  ggplot(aes(x = p, y=a_detection, color = method, group = method)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin =a_detection - 1.96*a_det_se, ymax= a_detection + 1.96*a_det_se), width = 0.1) +
  scale_x_log10(breaks=c(100,300,1000,3000,1e4), labels = scales::comma_format()) +
  facet_grid(detection~.) +
  lims(y = c(-0.1,1.1)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Set1") +
  geom_label_repel(data = df_detect %>%
  filter(d == 0.5, nsims == 10, n == 76, is.na(correlated), p == 10000), aes(label = method)) +
  labs()
```


## Nulls

no null results

```{r}
df_null %>%
  filter(d == 0.9) %>%
  print(n=25)
```

## Time

```{r}
df_time %>%
  ggplot(aes(p, mean_time, group = method, color = method)) +
  geom_line() +
  scale_y_log10() +
  scale_x_log10(breaks = c(1e2, 3e2, 1e3, 3e3, 1e4))
```

## AUC

```{r}
df_perf %>%
  filter(! method %in% c("tweedie", "fdr")) %>%
  ggplot(aes(x=p, y=test_auc, color= method)) +
  geom_line() +
  scale_x_log10(breaks = c(1e2, 3e2, 1e3, 3e3, 1e4))
```

